### PR TITLE
Verlet speedup

### PR DESCRIPTION
**Pull request by Tovermodus**

### CODE REVIEW

**Comment by Tovermodus** [comment]
Edited some of the comments from @nnjjtt in
> filestream f in plot_file /visualisation.py never gets a f.close(), calc energy in medium.cpp is missing the mass difference in m_g_h, Medium_parameters.h still has the missing brackets in the friction_rotation formula of the copy constructor. The diffusion quotients in move_random /medium.cpp seem to make sense, but do differ from the original paper.

How do the coefficients differ from the original paper? In Platti, Cuetos (2012) they define the amplitudes as $δr_‖ = \sqrt{2D_‖δt}$ which is the formula implemented in `Movement::Movement` and which was implemented in `TrialMedium::move_random`. Or is it in the formulas in `MediumParameters`?

**Comment by nnjjtt** [comment]
Well, I was working off Lebovka, Tarasevich, Bulavin, Kovalchuk, Vygornitskii (2019) where they say in a confusing manner as always:
 
> The amplitudes of the Brownian motions are proportional
to the square roots of the corresponding diffusion coefficients.
The amplitude of the displacement along the long axis was
put as r = αl, where α was chosen to be small enough
(α = 0.05) in order to obtain satisfactory acceptance of the
MC displacement [60].

**Comment by Tovermodus** [comment]
Our amplitudes are proportional to the square root but I took the other approach for the proportionality constant which is closer to the original theory of Brownian motion and does not rely on an additional parameter alpha

**Comment by nnjjtt** [comment]
Yes, I agree that that is the more physical approach, I just wanted to highlight it since it marks a deviation from this paper.

**Pull request merged**
